Issue 1 user can create entry
Jc-Leon/code-journal pull request #5
Opened 2021-07-14 20:22 UTC by Jc-Leon

https://user-images.githubusercontent.com/84432043/125687764-1e89e27d-b1ce-4c08-acab-74cb2b2b41bc.mov

2021-07-14 20:23 UTC, Jc-Leon commented
https://user-images.githubusercontent.com/84432043/125687966-5c95b78e-b27d-4c67-b4dd-c3b5ba559629.mov

2021-07-14 21:41 UTC, codingcodymiller requested changes

2021-07-14 21:41 UTC, codingcodymiller commented on index.html
> +        <div class="column-full">
You should put this in a `row` class element. In a grid layout class system there should always be container -> row -> column

2021-07-14 21:41 UTC, codingcodymiller commented on index.html
> +          <div class="column-half">
You should put this in a `row` class element. In a grid layout class system there should always be container -> row -> column

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +$input.addEventListener('input', function (event) {
Please use named functions, not anonymous functions

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +form.addEventListener('submit', function (event) {
Please use named functions, not anonymous functions

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +var entries = [];
These are not necessary, you should be using the data model we prepared for you in `data.js`

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +  localStorage.setItem('Values', JSON.stringify(entries));
All localStorage-related code should be in the `data.js` file, not `main.js`

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +  }
All localStorage-related code should be in the `data.js` file, not `main.js`

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +  // console.log(JSON.parse(objects));
Please remove commented code before submitting

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +  // console.log(newObj);
Please remove commented code before submitting

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +  document.getElementById('log').reset();
You already have a variable named `form` holding the form, you should use that variable instead of querying again

2021-07-14 21:41 UTC, codingcodymiller commented on js/main.js
> +var $img = document.querySelector('.img__holder');
Not sure why you have two underscores in your class names, please use `kebab-case`

2021-07-15 00:34 UTC, codingcodymiller requested changes

2021-07-15 00:34 UTC, codingcodymiller commented on css/styles.css
> +}
Instead of applying the same styling multiple times, you should make a reusable class with this styling that you can add to both of these elements.

2021-07-15 00:34 UTC, codingcodymiller commented on js/data.js
> +form.addEventListener('submit', function newObj() {
You should name this function something like `submitEntry`, `newObj` doesn't tell me its purpose and is also the name of a variable inside of this function, which is doubly bad news.

2021-07-15 00:34 UTC, codingcodymiller commented on js/data.js
> +  data.entries.unshift(newObj);
This should be in `main.js`. Only localStorage code and the `data` variable should be in `data.js`. I recommend looking back to the code for `javascript-local-storage` for a refresher, the code needed for localStorage for this project will be very nearly identical.

2021-07-15 00:34 UTC, codingcodymiller commented on js/data.js
> +  localStorage.setItem('Values', JSON.stringify(data.entries));
This should only be being done right before the page unloads, not after every submit. Also, you should be saving the entire `data` object in localStorage, not just `data.entries`

2021-07-15 16:28 UTC, codingcodymiller requested changes

2021-07-15 16:28 UTC, codingcodymiller commented on js/main.js
> +});
You shouldn't have two separate `submit` event handlers, you should add this work into the `submitEntry` function

2021-07-15 17:03 UTC, codingcodymiller approved these changes

2021-07-15 17:04 UTC, merged